<?php

namespace App\Services;

use Illuminate\Http\UploadedFile;

class CsvImportService
{
    /**
     * Read and parse an uploaded CSV file safely into associative rows.
     * Handles UTF-8 BOM, comma / semicolon delimiters, and empty paths.
     *
     * @param UploadedFile $file
     * @return array ['header' => array, 'rows' => array]
     * @throws \Exception
     */
    public static function parseCsv(UploadedFile $file): array
    {
        $content = '';
        
        // Try getting content directly from UploadedFile
        try {
            $content = $file->getContent();
        } catch (\Throwable $e) {
            $content = '';
        }

        // Fallback to path if getContent was empty
        if (empty($content)) {
            $path = $file->getPathname() ?: ($file->getRealPath() ?: null);
            if ($path && file_exists($path)) {
                $content = file_get_contents($path);
            }
        }

        if (empty($content)) {
            throw new \Exception('File yang diunggah kosong atau tidak dapat dibaca.');
        }

        // Strip UTF-8 BOM
        if (str_starts_with($content, "\xEF\xBB\xBF")) {
            $content = substr($content, 3);
        }

        // Standardize line breaks
        $content = str_replace(["\r\n", "\r"], "\n", $content);

        // Detect delimiter: comma (,) vs semicolon (;) commonly generated by Excel in ID locale
        $firstLine = strtok($content, "\n");
        $commaCount = substr_count($firstLine, ',');
        $semiCount = substr_count($firstLine, ';');
        $tabCount = substr_count($firstLine, "\t");

        $delimiter = ',';
        if ($semiCount > $commaCount && $semiCount > $tabCount) {
            $delimiter = ';';
        } elseif ($tabCount > $commaCount && $tabCount > $semiCount) {
            $delimiter = "\t";
        }

        // Open in-memory stream for robust RFC-compliant CSV parsing
        $handle = fopen('php://memory', 'r+');
        fwrite($handle, $content);
        rewind($handle);

        $rawHeader = fgetcsv($handle, 0, $delimiter);
        if (!$rawHeader || empty(array_filter($rawHeader))) {
            fclose($handle);
            throw new \Exception('File CSV tidak memiliki baris header yang valid.');
        }

        $header = array_map(function($h) {
            $normalized = strtolower(trim(preg_replace('/[\x00-\x1F\x7F\xEF\xBB\xBF]/', '', $h)));
            // Normalkan spasi (dan tanda hubung) menjadi underscore agar "nama kelas" == "nama_kelas"
            return preg_replace('/[\s\-]+/', '_', $normalized);
        }, $rawHeader);

        $rows = [];
        while (($line = fgetcsv($handle, 0, $delimiter)) !== false) {
            if (empty($line) || count(array_filter($line, fn($v) => trim($v) !== '')) === 0) {
                continue;
            }

            $data = [];
            foreach ($header as $idx => $colName) {
                $data[$colName] = isset($line[$idx]) ? trim($line[$idx]) : '';
            }
            $rows[] = $data;
        }

        fclose($handle);

        return [
            'header' => $header,
            'rows' => $rows,
        ];
    }
}
